
// This file has been generated by the GUI designer. Do not modify.
namespace GDScript_Shell
{
	public partial class PreferencesWindow
	{
		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TextView textview1;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget GDScript_Shell.PreferencesWindow
			this.Name = "GDScript_Shell.PreferencesWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("PreferencesWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child GDScript_Shell.PreferencesWindow.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textview1 = new global::Gtk.TextView();
			this.textview1.CanFocus = true;
			this.textview1.Name = "textview1";
			this.GtkScrolledWindow.Add(this.textview1);
			this.Add(this.GtkScrolledWindow);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		}
	}
}
