
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Button buttonFile;

	private global::Gtk.Button buttonEdit;

	private global::Gtk.Button buttonShell;

	private global::Gtk.Button buttonDebug;

	private global::Gtk.Button buttonOptions;

	private global::Gtk.Button buttonWindow;

	private global::Gtk.Button buttonHelp;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TextView shell;

	private global::Gtk.HBox hbox2;

	private global::Gtk.Label labelPos;

	private global::Gtk.Label bar;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("GDScript Shell");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Gravity = ((global::Gdk.Gravity)(5));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.HeightRequest = 39;
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.buttonFile = new global::Gtk.Button();
		this.buttonFile.Name = "buttonFile";
		this.buttonFile.UseUnderline = true;
		this.buttonFile.FocusOnClick = false;
		this.buttonFile.Relief = ((global::Gtk.ReliefStyle)(2));
		this.buttonFile.Label = global::Mono.Unix.Catalog.GetString("File");
		this.hbox1.Add(this.buttonFile);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.buttonFile]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.buttonEdit = new global::Gtk.Button();
		this.buttonEdit.Name = "buttonEdit";
		this.buttonEdit.UseUnderline = true;
		this.buttonEdit.FocusOnClick = false;
		this.buttonEdit.Relief = ((global::Gtk.ReliefStyle)(2));
		this.buttonEdit.Label = global::Mono.Unix.Catalog.GetString("Edit");
		this.hbox1.Add(this.buttonEdit);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.buttonEdit]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.buttonShell = new global::Gtk.Button();
		this.buttonShell.Name = "buttonShell";
		this.buttonShell.UseUnderline = true;
		this.buttonShell.Relief = ((global::Gtk.ReliefStyle)(2));
		this.buttonShell.Label = global::Mono.Unix.Catalog.GetString("Shell");
		this.hbox1.Add(this.buttonShell);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.buttonShell]));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.buttonDebug = new global::Gtk.Button();
		this.buttonDebug.Name = "buttonDebug";
		this.buttonDebug.UseUnderline = true;
		this.buttonDebug.Relief = ((global::Gtk.ReliefStyle)(2));
		this.buttonDebug.Label = global::Mono.Unix.Catalog.GetString("Debug");
		this.hbox1.Add(this.buttonDebug);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.buttonDebug]));
		w4.Position = 3;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.buttonOptions = new global::Gtk.Button();
		this.buttonOptions.Name = "buttonOptions";
		this.buttonOptions.UseUnderline = true;
		this.buttonOptions.Relief = ((global::Gtk.ReliefStyle)(2));
		this.buttonOptions.Label = global::Mono.Unix.Catalog.GetString("Options");
		this.hbox1.Add(this.buttonOptions);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.buttonOptions]));
		w5.Position = 4;
		w5.Expand = false;
		w5.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.buttonWindow = new global::Gtk.Button();
		this.buttonWindow.Name = "buttonWindow";
		this.buttonWindow.UseUnderline = true;
		this.buttonWindow.Relief = ((global::Gtk.ReliefStyle)(2));
		this.buttonWindow.Label = global::Mono.Unix.Catalog.GetString("Window");
		this.hbox1.Add(this.buttonWindow);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.buttonWindow]));
		w6.Position = 5;
		w6.Expand = false;
		w6.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.buttonHelp = new global::Gtk.Button();
		this.buttonHelp.Name = "buttonHelp";
		this.buttonHelp.UseUnderline = true;
		this.buttonHelp.Relief = ((global::Gtk.ReliefStyle)(2));
		this.buttonHelp.Label = global::Mono.Unix.Catalog.GetString("Help");
		this.hbox1.Add(this.buttonHelp);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.buttonHelp]));
		w7.Position = 6;
		w7.Expand = false;
		w7.Fill = false;
		this.vbox1.Add(this.hbox1);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
		w8.Position = 0;
		w8.Expand = false;
		w8.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.shell = new global::Gtk.TextView();
		this.shell.HeightRequest = 670;
		this.shell.CanFocus = true;
		this.shell.Name = "shell";
		this.shell.WrapMode = ((global::Gtk.WrapMode)(1));
		this.shell.LeftMargin = 10;
		this.GtkScrolledWindow.Add(this.shell);
		this.vbox1.Add(this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.GtkScrolledWindow]));
		w10.Position = 1;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.HeightRequest = 20;
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.labelPos = new global::Gtk.Label();
		this.labelPos.WidthRequest = 120;
		this.labelPos.Name = "labelPos";
		this.labelPos.Ypad = 10;
		this.labelPos.LabelProp = global::Mono.Unix.Catalog.GetString("Ln: XX Col: XX");
		this.hbox2.Add(this.labelPos);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.labelPos]));
		w11.PackType = ((global::Gtk.PackType)(1));
		w11.Position = 2;
		w11.Expand = false;
		w11.Fill = false;
		this.vbox1.Add(this.hbox2);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
		w12.Position = 2;
		w12.Expand = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.bar = new global::Gtk.Label();
		this.bar.HeightRequest = 1;
		this.bar.Name = "bar";
		this.bar.Ypad = 10;
		this.vbox1.Add(this.bar);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.bar]));
		w13.Position = 3;
		w13.Expand = false;
		w13.Fill = false;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 658;
		this.DefaultHeight = 763;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.KeyPressEvent += new global::Gtk.KeyPressEventHandler(this.OnKeyPressEvent);
		this.buttonFile.Clicked += new global::System.EventHandler(this.OnButtonFileClicked);
		this.buttonEdit.Clicked += new global::System.EventHandler(this.OnButtonEditClicked);
		this.buttonShell.Clicked += new global::System.EventHandler(this.OnButtonShellClicked);
	}
}
